version: '3'

services:
  db_python:
    image: postgres:13
    container_name: python_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
    ports:
      - "5432:5432"
