#Admin login
POST http://localhost:5000/login 
content-type: application/json

{
	"email": "admin@email.com",
	"password": "123"
}

###
#customer login
POST http://localhost:5000/login 
content-type: application/json

{
	"email": "user@email.com",
	"password": "123"
}

###
GET http://localhost:5000/car


### 

PUT http://localhost:5000/car/01adb8c3-e277-475d-ae27-96a4ef0d84a4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxNzE3OTQ5NywianRpIjoiZTJkOTg2ZjgtMGY2Yi00ZDVjLTkwODItMDNiZjk0N2Y5ZDZmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjRjYjNlNTE2LWQ1MDEtNGU2Zi05Yzk0LTA4OTRmM2Q5NTNjOSIsIm5iZiI6MTcxNzE3OTQ5NywiY3NyZiI6ImI3ZDNhY2QxLTQ1Y2ItNGYzZS05MDJlLTVmMzdjZTZjYmRkNCIsImV4cCI6MTcxNzE4MDM5N30.sLM3rdMzYDpE0C7auyt_f28sbqfmdjl7SOKV01Bb4hI

{
    "image_url": "https://quatrorodas.abril.com.br/wp-content/uploads/2016/11/57a23adf0e2163457524a26epalio_sporting_my2017_001.jpeg?quality=70&strip=all"
}

###

POST http://localhost:5000/user
Content-Type: application/json

{
    "username": "user",
    "email": "user2@email.com",
    "password": "123"
    
}

###

POST http://localhost:5000/car
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxNzE4MDc4OCwianRpIjoiYzQwYzZjMDAtNjk0Ni00MThiLWE0MDgtYWUxNzVlZjljYmQ0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImE3YTlhNTM5LTAzNjktNDZmMi04NGY3LTM1ZmVlM2RhNDYzMyIsIm5iZiI6MTcxNzE4MDc4OCwiY3NyZiI6IjE2OWUzYzYyLWU1YjEtNGZjZC05NmEzLWY2OTU0MDFmOGM5NyIsImV4cCI6MTcxNzE4MTY4OH0.zHFHL0ZCEb1j5HClF1DdQ5WI8yfQnuFFGJo59VQmIgo

{
    "name":"palio",
    "brand":"fiat",
    "model":"model 2020",
    "price": "61,450",
   "image_url":"https://www.google.com/url?sa=i&url=https%3A%2F%2Fquatrorodas.abril.com.br%2Fnoticias%2Fpalio-ganha-equipamentos-na-linha-2017-mas-sem-alteracao-nos-precos&psig=AOvVaw2VbJkxachA6WiJjNCFFYZL&ust=1716905268830000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCODY-NaAroYDFQAAAAAdAAAAABAE"
}

###

DELETE http://localhost:5000/car/f5fb1970-cd76-4d72-86ef-482d6998e323
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxNzE4MDc4OCwianRpIjoiYzQwYzZjMDAtNjk0Ni00MThiLWE0MDgtYWUxNzVlZjljYmQ0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImE3YTlhNTM5LTAzNjktNDZmMi04NGY3LTM1ZmVlM2RhNDYzMyIsIm5iZiI6MTcxNzE4MDc4OCwiY3NyZiI6IjE2OWUzYzYyLWU1YjEtNGZjZC05NmEzLWY2OTU0MDFmOGM5NyIsImV4cCI6MTcxNzE4MTY4OH0.zHFHL0ZCEb1j5HClF1DdQ5WI8yfQnuFFGJo59VQmIgo