"""add on table user default customer on role column

Revision ID: 7af5ab421ae4
Revises: e4121d4396d1
Create Date: 2024-05-27 08:37:13.167398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af5ab421ae4'
down_revision: Union[str, None] = 'e4121d4396d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
